#include <Windows.h>

#define IDBITMAP_LEAF		101
#define IDBITMAP_STAR		102
#define IDBITMAP_MOON		103
#define IDBITMAP_HEART		104
#define IDBITMAP_SIR		105
#define IDBITMAP_AMC		106
#define IDBITMAP_BARK		107
#define IDBITMAP_BACKRAIN	108
#define IDBITMAP_STUDYROOM	109
#define IDBITMAP_COLLAGE	110
#define IDBITMAP_HEART_PINK	111

